// This file is generated by npm run build:icons

export type IconName =
  | "check"
  | "chevron-down"
  | "circle"
  | "download"
  | "google"
  | "log-out"
  | "logo"
  | "plus"
  | "settings"
  | "spinner"
  | "square-pen"
  | "trash-2"
  | "users"
  | "x";
